version: "3"
services:
  mongo:
    container_name: mongo-qs
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    ports:
      - 27017:27017

  mongo-test:
    container_name: mongo-test
    image: mongo
    ports:
      - 27018:27017

  node:
    container_name: node
    build: .
    volumes:
      - ./:/server
    ports:
      - 3030:3030
    links:
      - mongo
    command:
      - /bin/sh
      - -c
      - npm install && npm run dev
